### ISSUE TITLE
Randomly getting org.iilab.pb/.CalculatorActivity  android.os.DeadObjectException

### ISSUE THREAD

**Issue by niccs** [PanicInitiative/PanicButton#136]
This exception is thrown randomly, while stress testing the PB alert trigger behavior. Need to reproduce this.

Following is the stack trace:--

12-02 12:06:48.902    780-16726/? W/ActivityManager﹕ Exception when starting activity org.iilab.pb/.CalculatorActivity
    android.os.DeadObjectException
            at android.os.BinderProxy.transactNative(Native Method)
            at android.os.BinderProxy.transact(Binder.java:503)
            at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:826)
            at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1284)
            at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1384)
            at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:1969)
            at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1554)
            at com.android.server.am.ActivityStack.resumeTopActivityLocked(ActivityStack.java:1537)
            at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:922)
            at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
            at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
            at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
            at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
            at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
            at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
            at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
            at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

**Comment by jmatsushita** [comment]
Do you think this is linked to #196 and #73 ?
