### ISSUE TITLE
crash when adding a contact

### ISSUE THREAD

**Issue by eighthave** [PanicInitiative/PanicButton#57]
I'm running PanicButton 1.3.0 from Google Play on a Samsung Note 2 running CyanogenMod 10.1 (Android 4.2).  When I click on the contact button next to the field to add a contact number, PanicButton crashes.  This seems to happen for all contacts.

I have submitted the crash to Google Play, and here is it from logcat:
```
      BluetoothAdapter  D  1103767408: getState() :  mService = null. Returning STATE_OFF
              dalvikvm  D  GC_EXPLICIT freed 430K, 5% free 23170K/24232K, paused 12ms+8ms, total 71ms
                Finsky  D  [1] DetailsDataBasedFragment.rebindViews: Page [class=DetailsFragment] loaded in [529787 ms] (hasDetailsDataLoaded? false)
                        D  [1] FastHtmlParser.fromHtml: Doing slow HTML parse due to unexpected tag <a href="h
                        D  [1] DetailsDataBasedFragment.rebindViews: Page [class=DetailsFragment] loaded in [529893 ms] (hasDetailsDataLoaded? true)
              dalvikvm  D  GC_CONCURRENT freed 2660K, 17% free 14693K/17532K, paused 2ms+5ms, total 32ms
                        D  WAIT_FOR_CONCURRENT_GC blocked 24ms
                 >>>>>  E  no update needed
          >>>>>>>>>>>>  E  starting next activity
                >>>>>>  E  first run FALSE, running CalculatorActivity
                 >>>>>  E  Registering Restart Install receiver
                        E  Registering Restart Install receiver
                        E  Registering finish activity in oncreate -> BaseFragmentActivity
 MainActivity.onCreate  E  pageId = home-ready
                 >>>>>  E  SimpleFragment.onCreateView
                        E  SimpleFragment.onActivityCreated
            TagHandler  D  Found an unsupported tag html
                        D  Found an unsupported tag body
                        D  Found an unsupported tag html
                        D  Found an unsupported tag body
SimpleFragment.onStart  E  home-ready
  MainActivity.onStart  E  .
 MainActivity.onResume  E  pageId = home-ready and flagRiseFromPause = false
impleFragment.onResume  E  home-ready
SimpleFragment.onPause  E  home-ready
  MainActivity.onPause  E  .
                        E  flagRiseFromPause = true
                 >>>>>  E  Registering finish activity in oncreate -> BaseFragmentActivity
 MainActivity.onCreate  E  pageId = settings
                 >>>>>  E  SimpleFragment.onCreateView
                        E  SimpleFragment.onActivityCreated
SimpleFragment.onStart  E  settings
  MainActivity.onStart  E  .
 MainActivity.onResume  E  pageId = settings and flagRiseFromPause = false
impleFragment.onResume  E  settings
 SimpleFragment.onStop  E  home-ready
   MainActivity.onStop  E  .
SimpleFragment.onPause  E  settings
  MainActivity.onPause  E  .
                        E  flagRiseFromPause = true
                 >>>>>  E  Registering finish activity in oncreate -> BaseFragmentActivity
 MainActivity.onCreate  E  pageId = settings-contacts
                ??????  E  text changed
                        E  text changed
                        E  text changed
            TagHandler  D  Found an unsupported tag html
                        D  Found an unsupported tag body
                        D  Found an unsupported tag html
                        D  Found an unsupported tag body
  MainActivity.onStart  E  .
 MainActivity.onResume  E  pageId = settings-contacts and flagRiseFromPause = false
 SimpleFragment.onStop  E  settings
   MainActivity.onStop  E  .
  MainActivity.onPause  E  .
                        E  flagRiseFromPause = true
ContactsIntentResolver  I  Called with action: android.intent.action.GET_CONTENT
   MainActivity.onStop  E  .
      ContactsProvider  D  Contacts query from application with privacy guard! pid=21860
        AndroidRuntime  D  Shutting down VM
              dalvikvm  W  threadid=1: thread exiting with uncaught exception (group=0x41876930)
        AndroidRuntime  E  FATAL EXCEPTION: main
                        E  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=196708, result=-1, data=Intent { dat=content://com.android.contacts/data/523647 flg=0x1 }} to act
                           ivity {org.iilab.pb/org.iilab.pb.MainActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                        E      at android.app.ActivityThread.deliverResults(ActivityThread.java:3447)
                        E      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3490)
                        E      at android.app.ActivityThread.access$1100(ActivityThread.java:153)
                        E      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1295)
                        E      at android.os.Handler.dispatchMessage(Handler.java:99)
                        E      at android.os.Looper.loop(Looper.java:137)
                        E      at android.app.ActivityThread.main(ActivityThread.java:5227)
                        E      at java.lang.reflect.Method.invokeNative(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:511)
                        E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                        E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
                        E      at dalvik.system.NativeStart.main(Native Method)
                        E  Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                        E      at android.database.AbstractCursor.checkPosition(AbstractCursor.java:424)
                        E      at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                        E      at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
                        E      at android.database.CursorWrapper.getString(CursorWrapper.java:114)
                        E      at org.iilab.pb.common.ContactPickerFragment.getPhoneNumber(ContactPickerFragment.java:86)
                        E      at org.iilab.pb.common.ContactPickerFragment.onActivityResult(ContactPickerFragment.java:78)
                        E      at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:161)
                        E      at android.app.Activity.dispatchActivityResult(Activity.java:5293)
                        E      at android.app.ActivityThread.deliverResults(ActivityThread.java:3443)
                        E      ... 11 more

```

**Comment by niccs** [comment]
Hi Jun,

For #57 ---When I click on the contact button next to the field to add a contact number, it crashes
the crash report says:-- (I think its not related to #81 )
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
Basically occurring at line 86 of file ContactPickerFragment
at org.iilab.pb.common.ContactPickerFragment.getPhoneNumber(ContactPickerFragment.java:86)

Seems, once we select a contact from the contact picker fragment, for some phones the cursor returned is blank
I have seen some related issues in StackOverflow, sometimes even though the contact number is there, still the cursor returned is blank. So in case of PB , I feel its better to check the cursor if its blank before fetching it.which is giving CursorIndexOutOfBoundException. Thers is no null or blank check  in code before fetching  the value from the cursor.

Existing code:--
cursor.moveToNext();
return cursor.getString(0);// the culprit statement

Its better if we change the code to

if(cursor.moveToNext()){
    phoneNumber=cursor.getString(0);
}
return phoneNumber;

Refer the links:--
http://stackoverflow.com/questions/14111003/empty-cursor-when-querying-contact-uri
http://stackoverflow.com/questions/13823097/querying-contacts-sometimes-returns-empty-cursor
