### ISSUE TITLE
Android Studio Set Up Failure

### ISSUE THREAD

**Issue by julihx** [PanicInitiative/PanicButton#76]
I have built the project on android studio and setup fails immediately i press get started button both on phone and emulator. I get a message Unfortunately,Calculate! has stopped

**Comment by jmatsushita** [comment]
Hi @julihx. We still use eclipse here but it would be great to move to android studio. Let us know if you still have the same problems with the latest 1.4.0 release that has been pushed to the master branch.

**Comment by julihx** [comment]
Thanks Jun,
  I have imported the latest version into android studio but i am still
having a problem.After debugging the project and installing into the phone,
the setup does not launch.I get a toast 'still to be implemented'
  I have shared the two projects on dropbox


Julius Gitonga

**Comment by jmatsushita** [comment]
Dear Julius,

I will install Android Studio on my machine and try to build the project. This issue is related to #51.

However let me share with you why I won't download zip files from dropbox to help you. One of the reasons is security, I wouldn't advise anyone to download and extract zip files like that from the internet, the other is that github is a tool specifically for developers to collaborate on open source project and it should be sufficient to help track bugs, discuss code and so on.

Can you give me more details about what you did and I'm sure I'll be able to help!

 * Which version of Android Studio are you using?
 * Are you using the master branch of Panic Button?
 * Did you create a project file for Android Studio?
 * Did you perform other steps to be able to build the project?
 * You mention "debugging" the project, do you mean you've been connected through ADB to a phone? Does this produce an error message? Or can you provide a screenshot?

If you have made some changes in order to build the project with Android Studio, could you please fork the Panic Button repository on your account, and publish the changes there? I noticed that you might have only recently joined Github, maybe I can suggest to read this article about contributing to open source projects? https://guides.github.com/activities/contributing-to-open-source/ 

Specifically you might want to also look into this article that explains how to use pull requests (https://help.github.com/articles/using-pull-requests/).

Warm welcome to the open source community and thank you for your interest in the Panic Button project!

Very best,

Jun

**Comment by jmatsushita** [comment]
Ok I've installed the latest Android Studio version 1.1.0 and imported the ADT project with the default options.

The first thing that's a potential problem is that the assets and res directory where moved so that might confuse the import of the json content files for the wizard. I'll create a new ```gradle``` branch for this. Please fork this if you're going to work on it.

**Comment by jmatsushita** [comment]
Of course, it wasn't as simple as I hoped. After using the import feature here's what I had to do:
 - Deal with missing dependencies in the root build.gradle file
 - For the android support-v4 library, I had to redownload the support library with the SDK manager.
 - I installed JUnit and robolectric support (http://tools.android.com/tech-docs/unit-testing-support https://github.com/robolectric/robolectric-gradle-plugin)

I've pushed the current work in progress on the ```gradle``` branch.

**Comment by julihx** [comment]
Jun,
 Thanks for your prompt response. I share your concerns about downloading and extracting zips files from the internet.I am new to Github and i have since forked the project and i will contribute as per the rules.Thanks for the guidance.
 I will give insights on what i have done so far.
    1.I am running android studio 1.1.0
    2.I cloned the master branch
    3.I imported the master branch to android studio using import project(Eclipse adt, Gradle) wizard on the quick start Menu. I tried to build the project and initially it had 101 errors mostly originating from wrong package path and missing libraries. I corrected the package path and added the following dependencies to build.gradle to solve missing libraries issue.
    compile files('libs/crashlytics.jar')
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.google.code.gson:gson:2.2.4'
    testCompile 'junit:junit:4.12'
    testCompile 'org.robolectric:robolectric:2.4'
    testCompile 'org.mockito:mockito-core:1.9.5'
4.With 0 errors and 0 warnings  i ran the project on the emulator. The app fails on the setup wizard after clicking the get started button. 
Here is a screenshoot 
   
![Uploading Capture.PNG . . .]()

**Comment by julihx** [comment]
![capture](https://cloud.githubusercontent.com/assets/11825115/7290492/78d080e2-e988-11e4-8157-bc924cf7b0bc.PNG)

**Comment by jmatsushita** [comment]
Maybe @jackygrahamez could help here. Hi Jacky. I just became aware of your work on your Panic Button fork and saw that you have migrated to Gradle with MayDay, so maybe you could help us here? I've posted my work in progress on the ```gradle``` branch.

Further progress today, I've added the compile statements to the gradle file.
Also ran into a crash problem apparently caused by LittleSnitch https://code.google.com/p/android/issues/detail?id=70592

Then I ran into the same problem as you and the logcat has the following error message which I'll look into now:
```
04-23 10:55:59.981    1756-1756/org.iilab.pb E/>>>>>﹕ Registering finish activity in oncreate -> BaseFragmentActivity
04-23 10:55:59.981    1756-1756/org.iilab.pb E/WizardActivity.onCreate﹕ pageId = setup-contacts
04-23 10:56:00.002    1756-1756/org.iilab.pb D/AndroidRuntime﹕ Shutting down VM
04-23 10:56:00.002    1756-1756/org.iilab.pb W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0xb4e0d908)
04-23 10:56:00.002    1756-1756/org.iilab.pb E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.iilab.pb/org.iilab.pb.WizardActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5039)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at org.iilab.pb.common.ContactEditTexts.findEditText(ContactEditTexts.java:45)
            at org.iilab.pb.common.ContactEditTexts.<init>(ContactEditTexts.java:37)
            at org.iilab.pb.fragment.SetupContactsFragment.onActivityCreated(SetupContactsFragment.java:148)
            at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1797)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:979)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at org.iilab.pb.WizardActivity.onStart(WizardActivity.java:210)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164)
            at android.app.Activity.performStart(Activity.java:5114)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
            at android.app.ActivityThread.access$600(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5039)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jackygrahamez** [comment]
@jmatsushita  I got your message, I'll look at it as soon as I have some free time. Maybe this weekend.

**Comment by jackygrahamez** [comment]
@jmatsushita I just built the gradle branch and got the same error

```Caused by: java.lang.NullPointerException
            at org.iilab.pb.common.ContactEditTexts.findEditText(ContactEditTexts.java:45)```

I recall there was a problem with the fragments and I got a lot of help on StackOverflow to get it working. I'm sure if you look at some of my code on the Gradle2 branch you will figure it out.
https://github.com/jackygrahamez/MayDay/tree/gradle2

Particularly take a look at this commit where I made many updates to the contact picker
https://github.com/jackygrahamez/MayDay/commit/b20da6d9a16174fe1b5e7a822f1747d1ad58baff?diff=split

Have a look at some of the replated StackOverflow posts as well
http://stackoverflow.com/questions/28660390/how-come-my-cursor-is-throwing-a-null-pointer-in-my-android-contact-picker

http://stackoverflow.com/questions/28665100/why-cant-i-update-my-view-fragment-phonenumberedittext

**Comment by niccs** [comment]
Hi Jun,

I am able to run the code in android-studio with few modifications. Can I contribute?

**Comment by jmatsushita** [comment]
Hi @niccs Yes, can you submit a pull request?

**Comment by niccs** [comment]
Thanks Jun, I have already sent the pull request few weeks back.

**Comment by jmatsushita** [comment]
Oops! Sorry about that. Will look at it today, thanks for your help!

**Comment by izzunmustaqim** [comment]
hi @niccs. can you help me how to run this project in android studio ?

**Comment by niccs** [comment]
Yes sure, share your email id for communication. Also where exactly are you
stuck??

**Comment by izzunmustaqim** [comment]
allright @niccs . my email id is izzunmustaqim@yahoo.com
